### ISSUE TITLE
Script fails if there are spaces in `searchRoots`

### ISSUE THREAD

**Issue by tndev** [ORESoftware/npm-link-up#53]
If the `searchRoots` contains spaces this part in [npm-link-up/lib/run-link.ts](https://github.com/ORESoftware/npm-link-up/blob/c9b6269b1a9b373980cf3ce38e0a3c57ebe32b64/lib/run-link.ts#L155) (maybe also other parts) would fail: 

```js
return ` cd ${p} && mkdir -p node_modules && rm -rf "node_modules/${name}" && mkdir -p "node_modules/${name}" ` +
` && rm -rf "node_modules/${name}" && ln -s "${path}" "node_modules/${name}" ` + ` ${getBinMap(bin, path, name)} `;
```
Escaping the space with `\\` would work for the `cd`but would then fail at another part of the code.

**Comment by ORESoftware** [comment]
thanks for the heads up - can you let me know what your exact input was? what does .nlu.json look like?

all the paths are double quoted so it should be able to handle spaces, but i will investigate.

**Comment by ORESoftware** [comment]
what version of nlu are you using?

**Comment by tndev** [comment]
nlu-version: 0.1.316
 
`.nlu.json`

```
{
  "$schema": "https://raw.githubusercontent.com/oresoftware/npm-link-up/master/assets/nlu.schema.json",
  "npm-link-up": true,
  "linkable": true,
  "linkToItself": false,
  "comments": [
    "your comments go here"
  ],
  "searchRoots": [
    "/home/niese/cloud/my library/node/__modular_test_project"
  ],
  "ignore": [
    "/node_modules/",
    "/.git/"
  ],
  "list": [
    "@tndev/module-a"
  ]
}
```

error message:

```
[nlu/info] First-pass script is => "cd /home/niese/cloud/my library/node/__modular_test_project/@tndev/application &&  mkdir -p node_modules && rm -rf "node_modules/@tndev/module-a" && mkdir -p "node_modules/@tndev/module-a" && rm -rf "node_modules/@tndev/module-a"  && ln -s "/home/niese/cloud/my library/node/__modular_test_project/@tndev/module-a" "node_modules/@tndev/module-a"  "
bash: line 1: cd: too many arguments
```

The problem is the `my library` because it would result in a `cd` with the arguments ` /home/niese/cloud/my` and `library/node/__modular_test_project/@tndev/application`

**Comment by ORESoftware** [comment]
yeah, all I need is quotes around `cd ${p}`, so it becomes `cd "${p}"` thanks for heads up, will fix right now

**Comment by ORESoftware** [comment]
before I publish, can you change the value in your node_modules folder and see it works for you?

**Comment by ORESoftware** [comment]
@tndev I just published a new version with a fix:   "version": "0.1.317", give that a shot, use the exact version in package.json for now.

**Comment by tndev** [comment]
Looks like this solved the problem.

It currently fails at another point, but I'm pretty sure that is another problem:

The error message is:
> npm ERR! code E404\nnpm ERR! 404 Not Found: @tndev/module-a@latest\n\nnpm ERR! A complete log of this run can be found in

I guess that's because the package is currently not published in npm.

**Comment by ORESoftware** [comment]
yeah that is a known issue, I am currently trying to devise a solution to that. right now, in order to use nlu yeah your package had to already be on NPM. at least it is a good excuse to grab the namespace on NPM before someone else does.

**Comment by ORESoftware** [comment]
hopefully it worked for you, feel free to comment if you have more questions
